######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 16:01:47 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
#CONFIG += debug
QT += sql xml network
HEADERS += color_wid.h best_results.h prog_update.h
SOURCES += color_wid.cpp main.cpp prog_update.cpp
